# Config
spring:
     # Spring Application Config
     application:
          name: ms-contract
     # Spring Cloud Config
     cloud:
          config:
               uri: http://localhost:8888
          
server:
     port: 8002

info.app.name: ms-contract
info.app.description: Microservices with Spring Boot and Spring Cloud - ms-contract
info.app.version: 0.0.1-SNAPSHOT