# Config
spring:
     # Spring Application Config
     application:
          name: ms-contract
     # Spring Cloud Config
     cloud:
          config:
               uri: http://localhost:8888
          
server:
     port: 8002

info.app.name: @project.name@
info.app.description: @project.description@
info.app.version: @project.version@